### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by VirUs-23** [VirUs-23/ClassiCube-VIP-VERSION#1]
hello guys its ClassiCube issues

**Comment by VirUs-23** [comment]
how to create folder
:((((((((((((((((

**Comment by VirUs-23** [comment]
for src
i want upload hacked client :-1: :100: :1234: :1st_place_medal:

**Comment by MLG-fun** [comment]
Click on New file
On the text field for the file name, first write the folder name you want to create
Then type /. This creates a folder
Give the new file a name and click Commit new file

Hope this helps

**Comment by VirUs-23** [comment]
thank you i gotta close this open issue

**Comment by VirUs-23** [comment]
ahahahahahahahaahhahahaha yes i break en
